name: radio_player
description: "A Flutter plugin to play streaming audio content with background support and lock screen controls."
version: 2.2.0
homepage: https://github.com/cheebeez/radio_player

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.cheebeez.radio_player
        pluginClass: RadioPlayerPlugin
      ios:
        pluginClass: RadioPlayerPlugin
